log_level = "debug"


# SMB 服务器相关配置区块
[smb]
# 如果地址为本地地址, 就进行本地备份
address = '\\10.10.0.201\backup'
username = "toor"
password = "1313243"


# 备份策略配置区块
[snapshot]
backup_exe_path = 'bin\snapshot64.exe'
command_exe_path = 'bin\sudo\gsudo.exe'

# 要备份的卷
backup_volumes = "C:" # 这将备份 C:
# volumes = "C:+D:+E:" # 同时备份 C：、D：和 E：
# volumes = "HD1:*" # 备份物理硬盘中的所有分区

# 备份的间隔时间, 避免重复备份 (h)
backup_interval = 0

limit_backup_files_count = 7

# 允许从备份中排除目录、文件或文件类型。
exclude = [
  # '\pagefile.sys',
  # '\hiberfil.sys',
  # '\swapfile.sys',
  # '\temp',
  '\*.tmp',
  '%temp%\*',
  # '\Windows\Temp\*',
  # '\$Recycle.Bin\*',
  # '\System Volume Information\*',
  # '\Windows\SoftwareDistribution\Download\*',
  # '\$WINDOWS.~BT\*',
  # '\$WINDOWS.~WS\*',
  # '\Windows.old\*',
]
# exclude = []


# 将目标硬盘的最大I/O速率限制为10MB/s（1-100）
limit_io_rate = 0
# 保存所有扇区，忽略空闲簇信息（维护）
save_all_sectors = false
# 如果从计划程序启动，则禁止 <按任何键>
disable_key = false
# 测试生成的映像文件（验证校验和是否正确）
test = false
# 命令行模式的图形状态显示
graph = false
# 备份前清空此驱动器的回收站
clean_recycle = false
